POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "A name",
  "number": "1223321"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "1223321"
}
